### ISSUE TITLE
Group Paths by Tag

### ISSUE THREAD

**Issue by RobWin** [atomfrede/generator-jhipster-spring-rest-docs#1]
Hi,

the generated HTML/PDF looks better, if you group the paths by tags/resources.

The Gradle script should look like this: 
```
convertSwagger2markup {
    dependsOn test
    inputDir swaggerOutputDir
    examplesDir asciiDocOutputDir
    pathsGroupedBy io.github.robwin.swagger2markup.GroupBy.TAGS
}
```

The HTML/PDF output looks like this then.

https://github.com/Swagger2Markup/swagger2markup/blob/master/images/Swagger2Markup.PNG

**Comment by atomfrede** [comment]
Thanks @RobWin for the tip. I will try to use it in the other generator if possible: https://github.com/atomfrede/generator-jhipster-swagger2markup

**Comment by RobWin** [comment]
Ups :)
